# Datadog Agent Configuration
# For AWS EC2 Ubuntu 26.04 Monitoring

api_key: YOUR_API_KEY_HERE
site: datadoghq.com

# Hostname
hostname: aws-ec2-sayali

# Tags
tags:
  - env:production
  - project:devops
  - cloud:aws
  - owner:sayali

# Log collection
logs_enabled: true

# Process monitoring
process_config:
  enabled: true

# Docker monitoring
docker_labels_as_tags:
  com.docker.compose.service: service_name
